# You can use this file to define resource usage estimates for Infracost to use when calculating
# the cost of usage-based resource, such as AWS S3 or Lambda.
# `infracost breakdown --usage-file infracost-usage.yml [other flags]`
# See https://infracost.io/usage-file/ for docs
version: 0.1
# resource_type_default_usage:
  ##
  ## The following usage values apply to each resource of the given type, which is useful when you want to define defaults.
  ## All values are commented-out, you can uncomment resource types and customize as needed.
  ##
  # aws_cloudwatch_log_group:
    # storage_gb: 0.0 # Total data stored by CloudWatch logs in GB.
    # monthly_data_ingested_gb: 0.0 # Monthly data ingested by CloudWatch logs in GB.
    # monthly_data_scanned_gb: 0.0 # Monthly data scanned by CloudWatch logs insights in GB.
  # aws_lb:
    # new_connections: 0 # Number of newly established connections per second on average.
    # active_connections: 0 # Number of active connections per minute on average.
    # processed_bytes_gb: 0.0 # The number of bytes processed by the load balancer for HTTP(S) requests and responses in GB.
    # rule_evaluations: 0 # The product of number of rules processed by the load balancer and the request rate.
  # aws_nat_gateway:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the NAT Gateway in GB.
  # aws_route53_record:
    # monthly_standard_queries: 0 # Monthly number of Standard queries.
    # monthly_latency_based_queries: 0 # Monthly number of Latency Based Routing queries.
    # monthly_geo_queries: 0 # Monthly number of Geo DNS and Geoproximity queries.
  # aws_vpc_endpoint:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the VPC endpoint(s) in GB.
# resource_usage:
  ##
  ## The following usage values apply to individual resources and override any value defined in the resource_type_default_usage section.
  ## All values are commented-out, you can uncomment resources and customize as needed.
  ##
  # aws_route53_record.this["*.navikun.com"]:
    # monthly_latency_based_queries: 0
    # monthly_geo_queries: 0
    # monthly_standard_queries: 0
  # aws_cloudwatch_log_group.this:
    # storage_gb: 0.0 # Total data stored by CloudWatch logs in GB.
    # monthly_data_ingested_gb: 0.0 # Monthly data ingested by CloudWatch logs in GB.
    # monthly_data_scanned_gb: 0.0 # Monthly data scanned by CloudWatch logs insights in GB.
  # aws_lb.this:
    # new_connections: 0 # Number of newly established connections per second on average.
    # active_connections: 0 # Number of active connections per minute on average.
    # processed_bytes_gb: 0.0 # The number of bytes processed by the load balancer for HTTP(S) requests and responses in GB.
    # rule_evaluations: 0 # The product of number of rules processed by the load balancer and the request rate.
  # aws_nat_gateway.nat_gateway1:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the NAT Gateway in GB.
  # aws_nat_gateway.nat_gateway2:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the NAT Gateway in GB.
  # aws_vpc_endpoint.cloudwatch_endpoint:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the VPC endpoint(s) in GB.
  # aws_vpc_endpoint.ecr_api:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the VPC endpoint(s) in GB.
  # aws_vpc_endpoint.ecr_dkr:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the VPC endpoint(s) in GB.
  # aws_vpc_endpoint.s3_endpoint:
    # monthly_data_processed_gb: 0.0 # Monthly data processed by the VPC endpoint(s) in GB.
